### ISSUE TITLE
Using CompressionLevel.NoCompression

### ISSUE THREAD

**Issue by Athimmas** [ashkan89/serilog-sinks-fileex#1]
I'm using CompressionLevel.NoCompression and retainedFileCountLimit its not possible to execute that action. Meanwhile if I remove the following code it is possible. What's the reason to decline that combination and is possible to remove that check?

        if (compressionLevel == CompressionLevel.NoCompression)
            throw new ArgumentException($@"{nameof(compressionLevel)} must not be 'NoCompression' when using {nameof(retainedFileCountLimit)}", nameof(compressionLevel));

**Comment by ashkan89** [comment]
I have Removed the unnecessary null check to have the possibility to use retainedFileCountLimit and CompressionLevel.NoCompression together but you have to set the targetDirectory if using nocompression.you can now update the package via nuget.It's available from 1.1.9 
@Athimmas

**Comment by Athimmas** [comment]
Thank you. This is great for folks who want to have more logs in archive then the limit.
